### ISSUE TITLE
Possible improvements for the current visualization strategy

### ISSUE THREAD

**Issue by nscapin** [p-costa/SNaC#20]
I would propose two improvements to the current visualization strategy and specifically in the phase of generation of the .xmf file:

1. Add the possibility for the user to choose which field should be loaded;
2. Add the possibility for the user to choose the frequency at which each field is loaded as some of them can be skipped and therefore should not be loaded.

**Comment by p-costa** [comment]
Thank you Nicolò, @nscapin!

* The choice of the fields to be loaded can be done during the visualization stage (at least in `paraview`), by choosing not to load these files.

* The frequency option (1) has been added in f56fa37 (see parameter `istep` which is set to `1`, constant spacing, by default).
